import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import React from 'react';
import {
  Layout,
  theme,
  Button,
  Col,
  Input,
  Row,
  Typography,
  Divider,
} from 'antd';
import { useEffect } from 'react';
import { AudioOutlined } from '@ant-design/icons';
import { MdOutlineMyLocation, MdLocationOn } from 'react-icons/md';
import { useRouter } from 'next/router';
import Cookies from 'js-cookie';
import { User } from './types/type';
const { Header, Content, Footer } = Layout;
const { Search } = Input;

const { Title } = Typography;

const prefix = (
  <MdLocationOn
    style={{
      fontSize: 25,
      color: '#1677ff',
    }}
  />
);

export default function Home() {
  const router = useRouter();
  const token = Cookies.get('token');
  useEffect(() => {
    const user: User = token ? JSON.parse(token) : null;
    if (user && user.role === 'customer') router.push('/home');
    if (user && user.role === 'merchants') router.push('/merchants/dashboard');
  }, [router, token]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
      </main>
    </>
  );
}

export const HomePage = () => {
  const router = useRouter();
  const {
    token: { colorBgContainer },
  } = theme.useToken();
  return (
    <Layout className="layout">
      <Header
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          background: colorBgContainer,
        }}
      >
        <Link href="/" style={{ marginTop: '30px' }}>
          <Image src="/home_logo.png" alt="" width={200} height={40} />
        </Link>
        <div style={{ display: 'flex', gap: '1em' }}>
          <Link href="/create_new">
            <Button
              style={{
                borderColor: '#00ff64',
                color: '#00ff64',
                fontWeight: 700,
                backgroundColor: '#f8fafc',
                borderRadius: 0,
                textTransform: 'uppercase',
              }}
            >
              Create one
            </Button>
          </Link>
          <Link href="/signin">
            <Button
              style={{
                backgroundColor: '#00ff64',
                color: '#f8fafc',
                borderColor: '#00ff64',
                fontWeight: 700,
                borderRadius: 0,
                textTransform: 'uppercase',
              }}
            >
              Sign in
            </Button>
          </Link>
        </div>
      </Header>
      <Content>
        <div
          className="site-layout-content"
          style={{ background: colorBgContainer, paddingBlock: 100 }}
        >
          <HeroContent />
          <ServiceOffer />
          <GetTheApp />
        </div>
      </Content>
      <Footer>
        <FooterContent />
      </Footer>
    </Layout>
  );
};

export const HeroContent = () => {
  return (
    <div
      style={{
        paddingTop: '5em',
        maxWidth: 1300,
        margin: '0 auto',
        justifyContent: 'center',
        justifySelf: 'center',
      }}
    >
      <Row
        className="hero-content-wrapper"
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '2em',
        }}
      >
        <Col
          flex="1 1 500px"
          className="hero-text-content"
          style={{ display: 'flex', justifyContent: 'center' }}
        >
          <div>
            <h4
              style={{
                fontSize: '1.5em',
                fontWeight: 100,
              }}
            >
              Deliver Happyness to your
              <code className="hero-slogan-rocket_link">Door Step!</code>
            </h4>
            <h1
              style={{
                fontSize: '4em',
                fontWeight: 900,
                backgroundImage: 'linear-gradient(60deg, #E21143, #FFB03A)',
                backgroundClip: 'text',
                WebkitBackgroundClip: 'text',
                color: 'transparent',
              }}
            >
              Be The Fastest In <br />
              Delivering Your <b className="hero-text_style_line">Food!</b>
            </h1>
            <Search
              className="hero-address-search-content"
              placeholder="Find Your Location"
              enterButton="Discover"
              size="large"
              style={{ marginTop: '2em' }}
              prefix={prefix}
              // onSearch={onSearch}
            />
          </div>
        </Col>
        <Col
          flex="1 1 500px"
          style={{ display: 'flex', justifyContent: 'center' }}
        >
          <div>
            <Image alt="" src="/chef.png" width={500} height={500} />
          </div>
        </Col>
      </Row>
    </div>
  );
};

export const ServiceOffer = () => {
  return (
    <div>
      <div style={{ textAlign: 'center' }}>
        <h3 style={{ fontSize: 25, color: '#00ff64' }}>What we Serve ?</h3>
        <Title level={4} style={{ fontSize: 30, fontWeight: 900 }}>
          Your Favorite Food <br />
          Delivery Partner
        </Title>
      </div>
      <Row
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '2em',
        }}
      >
        <Col
          style={{
            display: 'flex',
            flexDirection: 'column',
            textAlign: 'center',
            alignItems: 'center',
            justifyContent: 'center',
          }}
          flex="1 1 300px"
        >
          <Image alt="" src="/service_i/order_i.svg" width={300} height={300} />
          <div>
            <Title style={{ fontSize: 25, fontWeight: 800 }}>
              Easy To Order
            </Title>
            <h4>
              You only need a few steps
              <br /> in ordering foods
            </h4>
          </div>
        </Col>
        <Col
          style={{
            display: 'flex',
            flexDirection: 'column',
            textAlign: 'center',
            alignItems: 'center',
            justifyContent: 'center',
          }}
          flex="1 1 300px"
        >
          <Image
            alt=""
            src="/service_i/deliver_i.svg"
            width={300}
            height={300}
          />
          <div>
            <Title style={{ fontSize: 25, fontWeight: 800 }}>
              Fastest Delivery
            </Title>
            <h4>
              Delivery that is always
              <br /> ontime even faster
            </h4>
          </div>
        </Col>
        <Col
          style={{
            display: 'flex',
            flexDirection: 'column',
            textAlign: 'center',
            alignItems: 'center',
            justifyContent: 'center',
          }}
          flex="1 1 300px"
        >
          <Image
            alt=""
            src="/service_i/quality_i.svg"
            width={300}
            height={300}
          />
          <div>
            <Title style={{ fontSize: 25, fontWeight: 800 }}>
              Best Quality
            </Title>
            <h4>
              Not only fast for use
              <br /> quality is also number one
            </h4>
          </div>
        </Col>
      </Row>
    </div>
  );
};

export const GetTheApp = () => {
  return (
    <div>
      <Row
        style={{ textAlign: 'center', alignItems: 'center', marginTop: 100 }}
      >
        <Col flex="1 1 500px">
          <div>
            <h3 style={{ fontSize: 25, color: '#00ff64' }}>DOWNLOAD APP</h3>
            <Title level={2}>Get Started With EOT Today !</Title>
            <h3>
              Discover the food whenever <br />
              and whereever and get your food delivered quickly
            </h3>
            <Button type="dashed" style={{ marginBlock: 20 }}>
              DOWNLOAD NOW
            </Button>
          </div>
        </Col>
        <Col flex="1 1 500px">
          <Image alt="" src="/get_app.png" width={400} height={600} />
        </Col>
      </Row>
    </div>
  );
};

export const FooterContent = () => {
  return (
    <div>
      <Divider />
      <div style={{ textAlign: 'center' }}>&copy;2023 All Right Reserved</div>
    </div>
  );
};
